version: '3'

services:
  api:
    container_name: your-pokemon-api
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - 3333:3333
    volumes:
      - ./api:/app
  web:
    container_name: your-pokemon-web
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
    depends_on:
      - api
networks:
  app-network:
    driver: bridge